### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JarneClauw** [JarneClauw/dotfiles#1]
**Configs & Scripts**
- [ ] Bash
- [ ] Git
- [ ] Discord (BetterDiscord)
- [ ] Obsidian
- [ ] Neovim
- [ ] Backgrounds
- [ ] Spotify (Spicetify)
- [ ] ClamAV
- [ ] Backup
- [ ] Timeshift

**Scripts**
- [ ] Check if <app> exists
- [ ] Fedora after install script
- [ ] All in one script

**Comment by JarneClauw** [comment]
What could be better:
- Settings script
- Gnome tweaks script
- Gnome extensions script

New configs, updated scripts, ... always nice

**Comment by JarneClauw** [comment]
Started using NixOS and will use the existing configs. Configs will be added so i will probably need to redo some of the other scripts.

**Comment by JarneClauw** [comment]
Think i will do most configs in Nix, especially the ones with plugins since i find it a pain in the ass.
So maybe there's a better solution, old configs will stay. Also finding a way to deal with home path and such, absolute path aren't allowed or its impure...

**Comment by JarneClauw** [comment]
All of the above is done.
- [ ] Fixing Firefox config
- [ ] Neovim configuration
- [ ] Making a better structure, modularizing
- [ ] Fixing parts of Gnome
- [ ] LightDM
- [ ] XMonad
